debug: false
isEnabled: true
appVersion: latest
cron:
  defaultSchedule: "0 7,12,18-21 * * *"
  defaultStartDeadlineSeconds: 1200
  defaultTimezone: "Europe/Berlin"
  instances:
    bluesky:
      useCase: forward-bluesky-posts
      hasConfigMap: false
      hasSecret: true
      configs:
      - id: hotzo
        targetChat: "-1001604595097"
        env:
          BLUESKY__AUTHOR_ID: "elhotzo.bsky.social"
      - id: probahn
        schedule: "0,30 7-22 * * *"
        targetChat: "-1002474524986"
        env:
          BLUESKY__AUTHOR_ID: "pro-bahn.de"
    mail:
      useCase: forward-mails
      hasConfigMap: false
      hasSecret: true
      configs: []
    reddit:
      useCase: forward-reddit-posts
      hasConfigMap: true
      hasSecret: true
      configs:
      - id: schnecke
        schedule: "*/20 * * * *"
        targetChat: "-1002055910690"
        env:
          REDDIT__SOURCE_USERNAME: schneckedertzchen
          REDDIT__SUBREDDIT_FILTER: DeutscheComics
    rss:
      useCase: forward-rss-feed
      hasConfigMap: false
      hasSecret: false
      configs:
        - id: scaleway
          schedule: "23 */2 * * *"
          targetChat: "-1002673102174"
          env:
            RSS__FEED_URL: https://www.scaleway.com/en/docs/changelog/rss.xml
        - id: signal
          schedule: "42 14 * * *"
          targetChat: "133399998"
          env:
            RSS__FEED_URL: https://signal.org/blog/rss.xml
            RSS__ORDER: "reverse_chronological"
    mastodon:
      useCase: forward-toots
      hasConfigMap: true
      hasSecret: true
      configs: []
    xcode:
      useCase: forward-xcode
      hasConfigMap: false
      hasSecret: false
      configs:
        - id: xcode
          schedule: "0 7,12 * * *"
          targetChat: "-1001914864431"

mastodon:
  apiBase: "https://mastodon.social"
  clientId: jTRdISbXG5U1BDtHjYgjBIgmSTg2YAn-eK5mWcfGjbA
reddit:
  clientId: L1bt67W1iuqv255IpkiTYg
image:
  app: ghcr.io/preparingforexams/twittergram
