debug: false
appVersion: latest
cron:
  defaultSchedule: "0 7,12,18-21 * * *"
  defaultStartDeadlineSeconds: 1200
  defaultTimezone: "Europe/Berlin"
  instances:
    bluesky:
      useCase: forward-bluesky-posts
      hasConfigMap: false
      configs:
      - id: hotzo
        targetChat: "-1001604595097"
        env:
          BLUESKY_AUTHOR_ID: "elhotzo.bsky.social"
      - id: probahn
        schedule: "0,30 7-22 * * *"
        targetChat: "-1002474524986"
        env:
          BLUESKY_AUTHOR_ID: "pro-bahn.de"
    mail:
      useCase: forward-mails
      hasConfigMap: false
      configs:
      - id: dart
        schedule: "0 9,20 * * *"
        targetChat: "-1001708495465"
        env:
          MAIL_MAILBOX_NAME: Dart News
      - id: flutter
        schedule: "0 9,20 * * *"
        targetChat: "-1001893015795"
        env:
          MAIL_MAILBOX_NAME: Flutter Announcements
    reddit:
      useCase: forward-reddit-posts
      hasConfigMap: true
      configs:
      - id: schnecke
        schedule: "*/20 * * * *"
        targetChat: "-1002055910690"
        env:
          REDDIT_SOURCE_USERNAME: schneckedertzchen
          REDDIT_SUBREDDIT_FILTER: DeutscheComics
    mastodon:
      useCase: forward-toots
      hasConfigMap: true
      configs:
        - id: hotzo
          targetChat: "133399998"
          env:
            MASTODON_SOURCE_ACCOUNT: "@elhotzo@mastodon.social"
    xcode:
      useCase: forward-xcode
      hasConfigMap: false
      hasSecret: false
      configs:
        - id: xcode
          schedule: "0 7,12 * * *"
          targetChat: "-1001914864431"

mastodon:
  apiBase: "https://mastodon.social"
  clientId: jTRdISbXG5U1BDtHjYgjBIgmSTg2YAn-eK5mWcfGjbA
reddit:
  clientId: L1bt67W1iuqv255IpkiTYg
image:
  app: ghcr.io/preparingforexams/twittergram
