debug: false
appVersion: latest
cron:
  defaultSchedule: "0 7,12,18-21 * * *"
  defaultStartDeadlineSeconds: 1200
  defaultTimezone: "Europe/Berlin"
mastodon:
  apiBase: "https://mastodon.social"
  clientId: jTRdISbXG5U1BDtHjYgjBIgmSTg2YAn-eK5mWcfGjbA
reddit:
  clientId: L1bt67W1iuqv255IpkiTYg
image:
  app: ghcr.io/preparingforexams/twittergram
