cron:
  defaultSchedule: "0 7,12,18-21 * * *"
  defaultStartDeadlineSeconds: 1200
  defaultTimezone: "Europe/Berlin"
mail:
  token: ${MAIL_TOKEN}
mastodon:
  apiBase: "https://mastodon.social"
  clientId: jTRdISbXG5U1BDtHjYgjBIgmSTg2YAn-eK5mWcfGjbA
  clientSecret: ${MASTODON_CLIENT_SECRET}
reddit:
  clientId: L1bt67W1iuqv255IpkiTYg
  clientSecret: ${REDDIT_CLIENT_SECRET}
image:
  app: ${IMAGE_NAME}:${GITHUB_SHA}
sentry:
  dsn: ${SENTRY_DSN}
telegram:
  apiKey: ${TELEGRAM_TOKEN}
twitter:
  apiKey: ${TWITTER_TOKEN}
