apiVersion: batch/v1
kind: CronJob
metadata:
  name: bluesky-advent
spec:
  schedule: {{ .Values.cron.defaultSchedule }}
  startingDeadlineSeconds: {{ .Values.cron.defaultStartDeadlineSeconds }}
  timeZone: {{ .Values.cron.defaultTimezone }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 5
  suspend: {{ .Values.debug }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: {{ .Release.Name }}
          containers:
            - name: app
              image: {{ .Values.image.app }}:{{ .Values.appVersion }}
              args: [ forward-bluesky-posts ]
              env:
                - name: STATE_CONFIG_MAP_NAME_SUFFIX
                  value: advent-bluesky
                - name: TELEGRAM_TARGET_CHAT_ID
                  value: "-1001604944844"
                - name: BLUESKY_AUTHOR_ID
                  value: "garygrady.bsky.social"
              envFrom:
                - configMapRef:
                    name: base
                - secretRef:
                    name: base
                - secretRef:
                    name: bluesky
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  ephemeral-storage: 512Mi
