apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
spec:
  replicas: {{ if .Values.debug }}1{{ else }}0{{ end }}
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      serviceAccountName: {{ .Release.Name }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 2
      containers:
        - name: app
          image: {{ .Values.image.app }}:{{ .Values.appVersion }}
          command: [ "tini", "--" ]
          args:
            - sleep
            - infinity
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ ALL ]
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              ephemeral-storage: 4Gi
          env:
            - name: TELEGRAM_TARGET_CHAT_ID
              value: "133399998"
          envFrom:
            - configMapRef:
                name: base
            - secretRef:
                name: base
