apiVersion: batch/v1
kind: CronJob
metadata:
  name: mail-flutter
spec:
  schedule: "0 9,20 * * *"
  startingDeadlineSeconds: {{ .Values.cron.defaultStartDeadlineSeconds }}
  timeZone: {{ .Values.cron.defaultTimezone }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 5
  suspend: {{ .Values.debug | not }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: {{ .Release.Name }}
          containers:
            - name: app
              image: {{ .Values.image.app }}:{{ .Values.appVersion }}
              args: [ forward-mails ]
              env:
                - name: STATE_CONFIG_MAP_NAME_SUFFIX
                  value: flutter
                - name: TELEGRAM_TARGET_CHAT_ID
                  value: "-1001893015795"
                - name: MAIL_MAILBOX_NAME
                  value: Flutter Announcements
              envFrom:
                - configMapRef:
                    name: base
                - secretRef:
                    name: base
                - secretRef:
                    name: mail
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
