apiVersion: batch/v1
kind: CronJob
metadata:
  name: reddit-schneckedertzchen
spec:
  schedule: "*/20 * * * *"
  startingDeadlineSeconds: 900
  timeZone: {{ .Values.cron.defaultTimezone }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 5
  suspend: {{ .Values.debug }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: {{ .Release.Name }}
          containers:
            - name: app
              image: {{ .Values.image.app }}:{{ .Values.appVersion }}
              args: [ forward-reddit-posts ]
              env:
                - name: STATE_CONFIG_MAP_NAME_SUFFIX
                  value: schnecke
                - name: TELEGRAM_TARGET_CHAT_ID
                  value: "-1002055910690"
                - name: REDDIT_SOURCE_USERNAME
                  value: schneckedertzchen
                - name: REDDIT_SUBREDDIT_FILTER
                  value: DeutscheComics
              envFrom:
                - configMapRef:
                    name: base
                - configMapRef:
                    name: reddit
                - secretRef:
                    name: base
                - secretRef:
                    name: reddit
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  ephemeral-storage: 512Mi
