apiVersion: batch/v1
kind: CronJob
metadata:
  name: xcode
spec:
  schedule: "0 7,12 * * *"
  startingDeadlineSeconds: {{ .Values.cron.defaultStartDeadlineSeconds }}
  timeZone: {{ .Values.cron.defaultTimezone }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 5
  suspend: {{ .Values.debug | not }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: {{ .Release.Name }}
          containers:
            - name: app
              image: {{ .Values.image.app }}:{{ .Values.appVersion }}
              args: [ forward-xcode ]
              env:
                - name: STATE_FILE_PATH
                  value: /state/state_v2_xcode.json
                - name: TELEGRAM_TARGET_CHAT_ID
                  value: "-1001914864431"
              envFrom:
                - configMapRef:
                    name: base
                - secretRef:
                    name: base
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
