---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: base
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: scaleway-prep-funnelgram
    kind: ClusterSecretStore
  data:
    - secretKey: SENTRY_DSN
      remoteRef:
        key: "name:sentry-dsn"
        decodingStrategy: None
  dataFrom:
    - extract:
        key: "name:manual-secrets"
