---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: base
spec:
  secretStoreRef:
    name: doppler-prep
    kind: ClusterSecretStore
  target:
    name: base
  dataFrom:
    - find:
        path: "FUNNELGRAM_BASE_"
      rewrite:
        - regexp:
            source: "FUNNELGRAM_BASE_(.+)"
            target: "$1"
