---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bluesky
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: scaleway-prep-funnelgram
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "name:bluesky"
      rewrite:
        - transform:
            template: 'BLUESKY_{{ `{{ .value | upper }}` }}'
