---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mail
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: scaleway-prep-funnelgram
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "name:mail"
      rewrite:
        - regexp:
            source: "(.+)"
            target: "MAIL_$1"
