---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mastodon
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: scaleway-prep-funnelgram
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "name:mastodon"
