---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mastodon
spec:
  secretStoreRef:
    name: doppler-prep
    kind: ClusterSecretStore
  target:
    name: mastodon
  dataFrom:
    - find:
        path: "FUNNELGRAM_MASTODON_"
      rewrite:
        - regexp:
            source: "FUNNELGRAM_(.+)"
            target: "$1"
