apiVersion: v1
kind: ConfigMap
metadata:
  name: base
data:
  DOWNLOAD_DIR: "/tmp/twittergram"
  # What a silly way to do opt-ins to breaking changes
  PTB_TIMEDELTA: "true"
  TELEGRAM__UPLOAD_CHAT_ID: "1259947317"
  STATE__TYPE: "configmap"
  STATE__CONFIG_MAP_NAMESPACE: "{{ .Release.Namespace }}"
  STATE__CONFIG_MAP_NAME_PREFIX: "state"
