apiVersion: batch/v1
kind: CronJob
metadata:
  name: mail-flutter
spec:
  schedule: "0 9,20 * * *"
  startingDeadlineSeconds: {{ .Values.cron.defaultStartDeadlineSeconds }}
  timeZone: {{ .Values.cron.defaultTimezone }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          securityContext:
            fsGroup: 500
          volumes:
            - name: state
              persistentVolumeClaim:
                claimName: state
          containers:
            - name: app
              image: {{ .Values.image.app }}
              args: [ forward-mails ]
              env:
                - name: STATE_FILE_PATH
                  value: /state/state_v2_mail_flutter.json
                - name: TELEGRAM_TARGET_CHAT_ID
                  value: "-1001893015795"
                - name: MAIL_MAILBOX_NAME
                  value: Flutter Announcements
              envFrom:
                - configMapRef:
                    name: base
                - secretRef:
                    name: base
                - secretRef:
                    name: mail
              volumeMounts:
                - mountPath: /state
                  name: state
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
