apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secrets
data:
  TELEGRAM_TOKEN: {{ .Values.telegram.apiKey | quote }}
  TWITTER_TOKEN: {{ .Values.twitter.apiKey | quote }}
stringData:
  SENTRY_DSN: {{ .Values.sentry.dsn | quote }}
