---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: state
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: tweet
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 5
  startingDeadlineSeconds: 1200
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: state
              persistentVolumeClaim:
                claimName: state
          containers:
            - name: app
              image: {{ .Values.image.app }}
              args: [ forward-tweets ]
              env:
                - name: STATE_FILE_PATH
                  value: /state/state_v1.json
              envFrom:
                - secretRef:
                    name: secrets
              volumeMounts:
                - mountPath: /state
                  name: state
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
