apiVersion: batch/v1
kind: CronJob
metadata:
  name: tweet-hotzo
spec:
  suspend: true
  schedule: {{ .Values.cron.defaultSchedule }}
  startingDeadlineSeconds: {{ .Values.cron.defaultStartDeadlineSeconds }}
  timeZone: {{ .Values.cron.defaultTimezone }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: {{ .Release.Name }}
          containers:
            - name: app
              image: {{ .Values.image.app }}
              args: [ forward-tweets ]
              env:
                - name: STATE_CONFIG_MAP_NAME_SUFFIX
                  value: hotzo
                - name: TELEGRAM_TARGET_CHAT_ID
                  value: "-1001604595097"
                - name: TWITTER_SOURCE_ACCOUNT
                  value: elhotzo
              envFrom:
                - configMapRef:
                    name: base
                - secretRef:
                    name: base
                - secretRef:
                    name: twitter
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
